### ISSUE TITLE
Keycloak Docker Container keep restarting after deployment using Docker-Compose

### ISSUE THREAD

**Issue by azizul90** [AriHealth/hapi-fhir-jpaserver-oauth#38]
Hi, I`m set up the japaserver oauth using PostgreSQL database.  However, the I deploy it via Docker Compose, I noticed the Keycloak container keep restarting.  When I check the logs, it shows output below.

```
_PS D:\Github\hapi-fhir-jpaserver-oauth> docker logs keycloak
Added 'admin' to '/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json', restart server to load user
-b 0.0.0.0
/opt/jboss/tools/docker-entrypoint.sh: line 165: DB_ADDR: unbound variable
User with username 'admin' already added to '/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json'
User with username 'admin' already added to '/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json'_

```

This is the docker-compose.yml content.

```
version: '3'

services:


# PostgreSQL database for HAPI
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - postgres-oauth:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

  keycloak:
    image: jboss/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    ports:
      - 9090:8080
    restart: always

# CDR starter
  hapi-fhir:
    container_name: hapi-fhir
    build: .
    environment:
#       # Specify DB_VENDOR in .env if you want a non default db in HAPI
      DB_VENDOR: ${DB_VENDOR}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DB}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      OAUTH_URL: ${OAUTH_URL}  
      OAUTH_ENABLE: ${OAUTH_ENABLE}
    ports:
      - 8080:8080
    depends_on:
      - auth
#      - mysql
#      - mariadb
      - postgres
      - keycloak
    restart: always

# Auth service
  auth:
    image: arihealth/oauth-easy:latest
    container_name: auth
    environment:
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_REALM: ${KEYCLOAK_REALM}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}
    ports:
      - 8081:8081
    depends_on:
      - keycloak
    restart: always

volumes: 
  postgres-oauth:
    external: true
```

This for .env file content

```
# Docker folder where the shared volumes are mounted
# CONFIG_FOLDER=/home/docker

# Database configuration 
# DB_VENDOR selects de DB strategy. 
# It must be coherent with docker-compose.yaml, where database deployment is commented,
# so remember to uncomment the one you prefer
# DB_VENDOR= DERBY | MARIADB | POSTGRESQL | MYSQL
# Default DERBY

# In case DB_VENDOR is PostgreSQL
DB_VENDOR=POSTGRESQL
DB_USER=fhir
DB_PASSWORD=fhir
DB_DB=fhirdb
DB_HOST=postgres
DB_PORT=5432

# KeyCloak
KEYCLOAK_USER=admin
KEYCLOAK_PASSWORD=Pa55w0rd

# HAPI OAuth 2.0 configuration
# To enable OAuth OAUTH_ENABLE=true
OAUTH_URL=http://auth:8081/user
OAUTH_ENABLE=true

# KEYCLOAK AUTH
KEYCLOAK_URL=http://keycloak:8080/auth
KEYCLOAK_REALM=HAPIFHIR
KEYCLOAK_CLIENT_ID=hapifhir-client
```

Is there any configuration I need to configure ? Seems I have follow the guides provided but the keycloak container not able run properly.
